const mongoose = require('mongoose');
const Product = require('./models/product');
require('dotenv').config();


const stock = [ //default products db
  {
    id: 1,
    name: 'Speed Socket',
    company: 'Speedo',
    category: 'Water sport',
    gender: 'All',
    description: 'Professional goggle, recommended by the best swimmers in the world',    
    price: 30,
    items: 5,
    rate: 4,
    image: 'https://m.media-amazon.com/images/I/714KTdibf0L._AC_UL1500_.jpg',
  },
  {
    id: 2,
    name: 'Ab wheel',
    company: 'Adidas',
    category: 'Fitness & exercise',
    gender: 'All',
    description: 'Best core excessive for the abs',
    price: 25,
    items: 18,
    rate: 5,
    image: 'https://megasport.co.il/pub/media/catalog/product/_/a/_adidas_ab_wheel_3_.jpg',  
  },
  {
    id: 3,
    name: 'Pull up bar',
    company: 'Energym',
    category: 'Fitness & exercise',
    gender: 'All',
    description: 'Pull up for you lats',
    price: 80,
    items: 3,
    rate: 3,
    image:
      'https://mastersport.co.il/wp-content/uploads/2021/06/PULLUP-BAR-%D7%9E%D7%AA%D7%A7%D7%9F-%D7%9E%D7%AA%D7%97-%D7%9C%D7%A7%D7%99%D7%A8.jpg',
  },
  {
    id: 4,
    name: 'Silicone cap',
    company: 'Speedo',
    category: 'Water sport',
    gender: 'All',
    description: 'Tightened and professional waterproof cap for swimmers',
    price: 15,
    items: 30,
    rate: 5,
    image: 'https://cdn.yalla.co.il/media/v1/u8654/n/14494827402-1.jpg',
  },
  {
    id: 5,
    name: 'Equipment mesh, 35L',
    company: 'Speedo',
    category: 'General accessories',
    gender: 'All',
    description: `PVC free, Material: Polyester Dimensions: 68 x 49cm - 35lt capacity.`,
    price: 12,
    items: 8,
    rate: 4,
    image: 'https://img.joomcdn.net/16f2e8426cd7545fd9fa9125801cec1802c8d84f_original.jpeg',  
  },
  {
    id: 6,
    name: 'Juve bottle',
    company: 'Adidas',
    category: 'General accessories',
    gender: 'All',
    description: 'Compact plastic bottle for any kind of sport, 750ml. Dishwasher safe.', 
    price: 14,
    items: 50,
    rate: 3.5,
    image: 'https://mastersport.co.il/wp-content/uploads/2017/07/ADIDAS-JUVE-BOTTLE-FS0236.jpg',  
  },
  {
    id: 7,
    name: 'Yoga mattress',
    company: 'Israblof',
    category: 'Fitness & exercise',
    gender: 'All',
    description: 'Mattress for yoga/camping, 0.5kg length:1.75 m, width: 0.8 m, thickness: 0.35 cm',  
    price: 17,
    items: 8,
    rate: 2,
    image: 'https://d3m9l0v76dty0.cloudfront.net/system/photos/5172932/original/5cef326b04239447b286d564920ad356.jpg',   
  },
  {
    id: 8,
    name: 'Skip rope',
    company: 'York Fitness',
    category: 'Fitness & exercise',
    gender: 'All',
    description: 'Skip Rope is perfect for high intensity workouts. 244 cm long', 
    price: 7,
    items: 28,
    rate: 4,
    image: 'https://cdn.shopify.com/s/files/1/2294/9841/products/York-8-inch-Skip-Rope-60002-front_grande.jpg?v=1529749627',  
  },
  {
    id: 9,
    name: 'Powerfin pro',
    company: 'Arena',
    category: 'Water sport',
    gender: 'All',
    description: 'Short fins for competitive swimmers, to improve your kick (flutter/dolphin)', 
    price: 35,
    items: 4,
    rate: 4.5,
    image: 'https://www.swiminn.com/f/13689/136892819/arena-powerfin-pro-swimming-fins.jpg', 
  },
  {
    id: 10,
    name: 'Floating fins',
    company: 'Finis',
    category: 'Water sport',
    gender: 'All',
    description: 'Fins to help any swimmer develop their stroke technique using the Swim Smooth Coaching System', 
    price: 25,
    items: 14,
    rate: 3,
    image:
      'http://cdn.shopify.com/s/files/1/2725/0522/products/finis-floating-fins-flippers1_fe3c544f-778c-4c6a-8d2c-28bf84717679_1200x1200.jpg?v=1521801337',
  },
  {
    id: 11,
    name: 'Diving fins',
    company: 'Cressi',
    category: 'Water sport',
    gender: 'All',
    description: 'Comfortable fins to dive in water',
    price: 38,
    items: 30,
    rate: 3.5,
    image: 'https://ae01.alicdn.com/kf/HTB1sGLlcMoQMeJjy0Fpq6ATxpXaa/Cressi.jpg',
  },
  {
    id: 12,
    name: 'Monofin',
    company: 'Finis',
    category: 'Water sport',
    gender: 'All',
    description: 'Fins for practice dolphin kick',
    price: 45,
    items: 10,
    rate: 3,
    image:
      'https://static.wixstatic.com/media/aa984c_e846787ad29c4be1bbc420a1ded79021~mv2.jpg/v1/fill/w_1000,h_1000,al_c,q_85/aa984c_e846787ad29c4be1bbc420a1ded79021~mv2.jpg',
  },
  {
    id: 13,
    name: 'Swimming paddles',
    company: 'Speedo',
    category: 'Water sport',
    gender: 'All',
    description: 'Paddles increase your the resistance with water and make you pull harder',
    price: 18,
    items: 50,
    rate: 5,
    image: 'https://s3.thcdn.com/widgets/241-en/27/Speedo-SwimTraining-TechPaddle1-Hero-600x600-102927.png',
  },
  {
    id: 14,
    name: 'Swimsuit',
    company: 'Speedo',
    category: 'Water sport',
    gender: 'Female',
    description: 'Tightened swimsuit for any activity. Endurance!',
    price: 34,
    items: 10,
    rate: 5,
    image: 'https://cdn.bike24.net/i/mb/41/66/ec/speedo-womens-placement-laneback-swimsuit-hex-black-oxid-grey4-837978.jpg',    
  },
  {
    id: 15,
    name: 'Fast skin swimsuit',
    company: 'Speedo',
    category: 'Water sport',
    gender: 'Male',
    description: 'Tightened swimsuit for competitions.',
    price: 200,
    items: 5,
    rate: 5,
    image: 'https://www.swiminn.com/f/13792/137927427/speedo-fastskin-lzr-pure-valor-jammer.jpg',   
  },
  {
    id: 16,
    name: 'Swimsuit',
    company: 'Speedo',
    category: 'Water sport',
    gender: 'Male',
    description: 'Tightened swimsuit for any activity. Endurance!',
    price: 20,
    items: 5,
    rate: 5,
    image: 'https://m.media-amazon.com/images/I/518fnjuDNqL._AC_SL1000_.jpg',
  },
  {
    id: 17,
    name: 'Goggle for kids',
    company: 'Corona',
    category: 'Water sport',
    gender: 'Kids', 
    description: 'Comfortable goggles for kids.',
    price: 8,
    items: 54,
    rate: 4.5,
    image: 'https://m.media-amazon.com/images/I/61ElkGD1EqS._AC_SL1500_.jpg',
  },
  {
    id: 18,
    name: 'Fast skin swimsuit',
    company: 'Speedo',
    category: 'Water sport',
    gender: 'Female',
    description: 'Tightened swimsuit for competitions.',
    price: 400,
    items: 4,
    rate: 5,
    image: 'https://media.alltricks.com/hd/18559945fc74dc98932d8.46295307.jpg',
  },
  {
    id: 19,
    name: 'Full carbon racquet',
    company: 'Speedo',
    category: 'Team sport',
    gender: 'All',
    description: 'Lightweight & professional racquet to play in open space.',
    price: 100,
    items: 3,
    rate: 5,
    image:
      'https://mastersport.co.il/wp-content/uploads/2019/07/%D7%9E%D7%98%D7%A7%D7%95%D7%AA-%D7%A7%D7%A8%D7%91%D7%95%D7%9F-%D7%9C%D7%99%D7%9D-TING-TONG.jpg',
  },
  {
    id: 20,
    name: 'Bodybuilding supplement',
    company: 'Combat',
    category: 'Nutrition',
    gender: 'All',
    description: 'Proteins for preparing a shake. 100% whey',
    price: 60,
    items: 30,
    rate: 5,
    image: 'https://cdn.azrieli.com/Images/c85c4bdf-e06b-4eed-b51f-e11579831782/Normal/2ffe1dc7.jpg',
  },
  {
    id: 21,
    name: 'Protein bar',
    company: 'Quest',
    category: 'Nutrition',
    gender: 'All',
    description: 'Proteins snack, flavour: Cookies & cream. Low sugar',
    price: 6,
    items: 130,
    rate: 3,
    image: 'https://vitamins-ninja.com/wp-content/uploads/2018/03/Untitled-design-22-1-800x800.png', 
  },
  {
    id: 22,
    name: 'R 7 comp 20',
    company: 'Rainbow',
    category: 'Cycling',
    gender: 'Kids',
    description: 'Mountain bike',
    price: 480,
    items: 12,
    rate: 3.5,
    image: 'https://momentum-bikes.co.il/wp-content/uploads/2020/11/1-7.jpg',
  },
  {
    id: 23,
    name: 'Short swimsuit',
    company: 'Timberland',
    category: 'Water sport',
    gender: 'Kids',
    description: 'Swimsuit for pool and sea water',
    price: 12,
    items: 27,
    rate: 4,
    image: 'https://cdn.azrieli.com/Images/87ac5c14-0d6c-4b7a-9e8c-bbcb613ef3d4/Normal/dbc16679.jpg',  
  },
  {
    id: 24,
    name: 'Short swimsuit',
    company: 'Diesel',
    category: 'Water sport',
    gender: 'Male',
    description: 'Swimsuit for pool and sea water',
    price: 15,
    items: 25,
    rate: 4,
    image: 'https://ricco.co.il/wp-content/uploads/2021/04/OIBAZ-400x533.jpg',
  },
  {
    id: 25,
    name: 'Speedy G3',
    company: 'Hoka',
    category: 'Running & walking',
    gender: 'Male',
    description: 'Running shoes with the newest technology',
    price: 100,
    items: 30,
    rate: 3,
    image: 'https://www.finder.co.il/wp-content/uploads/2020/05/2-HOKA-One-One-Carbon-X-768x461-1.webp',   
  },
  {
    id: 26,
    name: 'Zoomx',
    company: 'Nike',
    category: 'Running & walking',
    gender: 'Female',
    description: 'Running shoes for any kind of field',
    price: 85,
    items: 22,
    rate: 3.5,
    image: 'https://www.finder.co.il/wp-content/uploads/2020/05/4-6.webp',
  },
  {
    id: 27,
    name: 'Terminal x',
    company: 'Nike',
    category: 'Fitness & exercise',
    gender: 'All',
    description: 'Gloves for preventing blisters',
    price: 15,
    items: 22,
    rate: 3.5,
    image:
      'https://media.terminalx.com/pub/media/catalog/product/cache/f112238e8de94b6d480bd02e7a9501b8/x/1/x175580008-71551272027.jpg',
  },
  {
    id: 28,
    name: 'Leather basketball',
    company: 'Spalding',
    category: 'Team sport',
    gender: 'All',
    description: 'The formal basketball for the NBA',
    price: 27,
    items: 32,
    rate: 0,
    image: 'https://cdn.azrieli.com/Images/6cccbb63-8ed6-41dc-8d28-65459736d63c/Normal/f9baf4f4.jpg',  
  },
  {
    id: 29,
    name: 'Soccer ball',
    company: 'Fila',
    category: 'Team sport',
    gender: 'All',
    description: 'Leather soccer ball, best seller in Australia',
    price: 20,
    items: 11,
    rate: 5,
    image:
      'https://www.target.com.au/medias/static_content/product/images/full/47/21/A1684721.jpg?impolicy=product_portrait_hero',
  },
];

async function seed() {
  await mongoose.connect(process.env.db);

  for (let product of stock) {
      const p = await new Product({
        name: product.name,
        company: product.company,
        category: product.category,
        gender: product.gender,
        description: product.description,
        price: product.price,
        items: product.items,
        rate: product.rate,
        image: product.image,
      }).save();
  }

  mongoose.disconnect();

  console.info('Done!');
}

seed();
 